{% set name = "fiscalyear" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12857a48bd7b97bda78d833b29e81f30ec5aa018241f690e714b472b25fa1b47

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - fiscalyear

about:
  home: https://github.com/adamjstewart/fiscalyear
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Utilities for managing the fiscal calendar
  description: |
    fiscalyear is a small, lightweight Python module providing helpful utilities
    for managing the fiscal calendar. It is designed as an extension of the
    built-in datetime and calendar modules, adding the ability to query the fiscal
    year, fiscal quarter, fiscal month, and fiscal day of a date or datetime object.

  doc_url: https://fiscalyear.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/adamjstewart/fiscalyear

extra:
  recipe-maintainers:
    - CurtLH
    - adamjstewart
